<a href="https://colab.research.google.com/github/Prajaktahz/Uni_Colab_Work/blob/main/FBA_Week_08_Python_Test_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](http://www.cs.nott.ac.uk/~pszgss/teaching/nlab.png)
# FBA Python Test 2023

* You have one hour to finish this test.
* Please enter your answers into the spaces provided.
* We recommend that you show comments in your code, to evidence your work if possible (comments may earn some credit even if your script code is not 100% correct).
* In this test you will not be marked on elegance or efficiency, but rather getting the correct result in the instructed manner.
* Partial answers can still gain some marks, so please move onto the next question if you get stuck.
* As a guideline, question 5 is roughly halfway through the test.
* When you finish **do not forget to download your work as .ipynb file and upload it using Moodle submission link before 10:35 AM**.

## Your Name

Please print out your full name in the box below

In [1]:
#print out your full name here
'Prajakta Harihar Zaavde'

'Prajakta Harihar Zaavde'

## Section 1 - Variables, Types & Casting

### Q1.1: Variable assignment (2 marks)

Store your university login as a string (e.g. mine is lizel) in a variable **login** and print the type of your variable.

In [2]:
#enter your answer here
login = 'lixpz19'
print(type(login))

<class 'str'>


### Q1.2: Data Types & Casting  (3 marks)

In this question we want to:
* Assign to a variable **a** the integer value of 2
* Assign to a variable **b** the float value of 16.8
* Assign to a variable **c** the string value of '9.3'
* Assign to a variable **d** the sum of **a**, **b** and **c** (you will need to convert a variable from one type to another).
* Print the value of the variable **d** (the correct answer is 28.1)

In [3]:
#enter your answer here
a = 2
b = float(16.8)
c = '9.3'
d = float(a) + b + float(c)
print(d)

28.1


## Section 2 - Loops & Conditionals

In this section, your goal is to print every 4th number between 1 and 40 (that is: 4, 8, 12, 16, 20, 24, 28, 32, 36, 40). You will be asked to do this in several ways, using different python functions. Please complete these below:

### Q2.1: Use a for loop and the range() function (3 marks)

In [6]:
#enter your answer here
for i in range(0,41,4):
  print(i)

0
4
8
12
16
20
24
28
32
36
40


### Q2.2: Use a while loop - 1 (3 marks)

This time we want to use a while loop with a counter. The condition of your while loop should depend on a variable you create to count where you are in the loop.

In [7]:
#enter your answer here
i = 0
while(i < 41):
  print(i)
  i = i+ 4

0
4
8
12
16
20
24
28
32
36
40


### Q2.3: Use a while loop - 2 (3 marks)

This time we want to use a counter and a 'while True' loop (infinite loop). You must exit the loop using the **continue** or **break** statement (n.b. only one of these two commands will do what you want), and any other commands that you think are useful.

In [9]:
#enter your answer here
i = 0
while(True):
  if(i < 41):
    print(i)
    i = i + 4
    continue
  else:
    break

0
4
8
12
16
20
24
28
32
36
40


## Section 3 - If statements

### Q3.1: Using if, elif and else (3 marks)
Given a variable **x** containing a number, write a script that does the following:
- If the number in **x** is negative or equal to zero, print : 'The number is negative or zero'
- If the number in **x** is positive and even, print: 'The number is positive and even'
- If the number in **x** is positive and odd, print: 'The number is positive and odd'

Remember that you have to use **if**, **elif** and **else** in this question.

In [14]:
x = 2 # You can change the value of x to -3, 0, 2, 9 to cover the different cases and test your code
if(x <= 0):
  print('The number is negative or zero')
elif(x > 0 and x%2 == 0):
  print('The number is positive and even')
else:
  print('The number is positive and odd')
#enter your answer here

The number is positive and even


### Q3.2: Nested conditionals (3 marks)
Finally, (and given the same variable **x**) please use <i>nested</i> if statements to cover the following cases:
- If the number is negative or equal to zero:
    - And if the number is even, print: 'The number is negative or zero and even'
    - And if the number is odd, print: 'The number is negative or zero and odd'
- If the number is positive:
    - And if the number is even, print: 'The number is positive and even'
    - And if the number is odd, print: 'The number is positive and odd'

In [22]:
x = 0 # You can change the value of x to -3, 0, 2, 9 to cover the different cases and test your code
if( x <= 0):
  if(x%2 == 0):
    print('The number is negative or zero and even')
  else:
    print('The number is negative or zero and odd')
else:
  if(x%2 == 0):
    print( 'The number is positive and even')
  else:
    print('The number is positive and odd')
#enter your answer here

The number is negative or zero and even


### Q3.3: Type Checking (3 marks)

This time you are asked to work with two variables **a** and **b**. Write an if statement that prints on the screen the sum of a and b if both variables are integers. Otherwise, print on the screen the following message: 'Both variables need to be integers'.

In [27]:
a = 2
b = 'Hello' # You can change the values of a and b to cover the different cases and test your code
if(type(a) == int and type(b) == int):
  c = a + b
  print(c)
else:
  print('Both variables need to be integers')
#enter your answer here

Both variables need to be integers


## Section 4 - Data Structures

### Q4.1: List creation (2 marks)

Create a list that contains 4 elements: 'a', 'b', 'b' and 'd' and assign it to a variable **l**.

In [28]:
#enter your answer here
l = ['a','b','b','d']

### Q4.2: List Length (1 mark)

Print the length of your list

In [29]:
#enter your answer here
print(len(l))

4


### Q4.3: List modification (2 marks)

Update your list and change the third element (currently the second 'b') to a 'c' so that your list becomes 'a','b','c' and 'd', and then print it out.

In [30]:
#enter your answer here
l.insert(2,'c')
print(l)

['a', 'b', 'c', 'b', 'd']


### Q4.4: List indexing (2 marks)

Using two different ways of indexing, print the last element of your list (i.e. 'd')

In [35]:
#enter your answer here
print(l.index('d'))


for i in range(len(l)):
 if(l[i] == 'd'):
  print(i)

4
4


### Q4.5: Dictionary Creation (3 marks)

Create and assign to a variable **dict1** a dictionary that contains the following key value pairs (using one line of code):

|key|value|
|-|-|
|ID|1|
|Gender|Male|
|Age|19|
|Income|15000|
|Spending_score|39|

In [36]:
#enter your answer here
dict1 = {'ID':1, 'Gender':'Male','Age': 19,'Income':15000,'Spending_score': 39}

### String Manipulation

This time you are given a string **s** that contains 5 comma-separated values in that order:
1. Customer ID
2. Gender
3. Age
4. Income (k£)
5. Spending Score (between 1 and 100)

In the next two questions, we will want to transform that string into a dictionary similar to the one we have just done.

### Q4.6: Splitting text (2 marks)
The first step (this question), is to split the string to obtain a list of strings, stored in a variable **split_list** and whose elements contains the data held in the string.

In [37]:
s = "1,Male,19,15,39"
#enter your answer here
split_list = s.split(',')
print(split_list)

['1', 'Male', '19', '15', '39']


### Q4.7: Populating an empty dictionary (5 marks)

This time  first create an empty dictionary and assign it to a variable **dict2**. Then, we want to populate the dictionary, using the data from our list stored in **split_list**. The 1st element is the ID, the 2nd - the Gender, the 3rd - Age, the 4th - Income and the last element is the Spending_score.

(n.b. if you didn't manage to extract the list in the previous question, please create your own version of **split_list** manually)

Remember the two steps of this question:
1. Create an empty dictionary and assign it to a variable **dict2**
2. Populate your dictionary by adding new keys and assigning it the values from your **split_list** converted into the appropriate datatypes.

In [38]:
#enter your answer here
dict2 = {}

dict2['ID'] = int(split_list[0])
dict2['Gender'] = str(split_list[1])
dict2['Age'] = int(split_list[2])
dict2['Income'] = int(split_list[3])
dict2['Spending_score'] = int(split_list[4])

print(dict2)


{'ID': 1, 'Gender': 'Male', 'Age': 19, 'Income': 15, 'Spending_score': 39}


### Q4.8: Updating values in a dictionary (2 marks)

The income was given to us in k£ (i.e., 15 corresponds to £15000). For clarity we want to update our 'income' value in the dictionary by multiplying it by 1000 so that we have a meaningful number. Once done, print your dictionary.

(n.b. again, if you didn't succeed in the previous question, feel free to create your own version of **dict2** explicitly in the first line).

In [39]:
#enter your answer here
dict2['Income'] = dict2['Income'] * 1000
print(dict2)

{'ID': 1, 'Gender': 'Male', 'Age': 19, 'Income': 15000, 'Spending_score': 39}


## Section 5 - Functions

### Q5.1: A Basic function (2 marks)

Create a function **say_hello** that prints on the screen 'Hello' when you call it. Add a call to your function after its definition to check if it works as expected.

In [40]:
#enter your answers here
def say_hello():
  print('Hello')

say_hello()

Hello


### Q5.2: Function parameters  (2 marks)

Create a function called **say_hello_to** that has a parameter **name** and prints 'Hello John' if you pass it the name 'John' as an argument. Add a call to your function after its definition to check if it works as expected.

In [42]:
#enter your answer here
def say_hello_to(name):
  print('Hello ' + str(name))

say_hello_to('John')

Hello John


### Q5.3: Returning a value (2 marks)

Create a function **my_multiplication** that takes two parameters a and b and returns the product of a and b. Two function calls have been added with the expected return values so that you can check your function behavior.

In [43]:
#enter your answer here
def my_multiplication(a,b):
  return a*b
#test using the following function calls
print(my_multiplication('Hello ', 3)) # Should print 'Hello Hello Hello'
print(my_multiplication(2, 3)) # Should print 6

Hello Hello Hello 
6


### Q5.4: A function to extract the mode (8 marks)

Write a function **extract_mode** that takes a list **lst** as a parameter and returns the mode of the list. **You *must* use a dictionary** as part of your function.

Only use the core python data-types and functions to answer this question. (i.e. lists, dictionaries, if statements, for / while loops, ...)

In [49]:
lst1 = [1, 2, 3, 4, 5, 6, 6, 6, 7] # Correct answer : 6
lst2 = ['Monday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] # Correct answer : 'Monday'

#enter your answer here
def extract_mode(lst):
  dict_list = {}
  unique_val = []

  for i in lst:
    if(i not in unique_val):
      unique_val.append(i)

  for i in unique_val:
    dict_list[i] = lst.count(i)
  return max(zip(dict_list.values(), dict_list.keys()))[1]

print(extract_mode(lst1))
print(extract_mode(lst2))

6
Monday


## Section 6 - Module Import & Documentation

### Q6.1: Importing a module (1 mark)

Import the module **NumPy** with the usual shortcut name **np**

In [50]:
#enter your answer here
import numpy as np

### Q6.2: Ndarray Creation (2 marks)

You are given a variable **mat_data** containing nested lists. Create a NumPy array from the variable **mat_data** and assign it to a variable **mat**. Print your array.

In [52]:
mat_data = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

mat = np.array(mat_data)
#enter your answer here
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Q6.3: Ndarray Shape (2 marks)

Print the shape of your array.

In [53]:
#enter your answer here
mat.shape

(3, 4)

### Q6.4: Mean (3 marks)

What is the mean of each row of the matrix **mat**? Print your result. Please use a function in NumPy to do this (if needed, refer to the NumPy documentation to find the function to use and check its parameters).

In [55]:
#enter your answer here
np.mean(mat, axis= 1)

array([ 2.5,  6.5, 10.5])

### Q6.5: Transpose (2 marks)

Assign to a variable **mat_t** the transpose of the matrix **mat** using a NumPy function and print it.

In [56]:
#enter your answer here
mat_t = np.transpose(mat)
print(mat_t)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


### Q6.6: Cubing (3 marks)

By whatever means you see appropriate, cube (i.e. exponent 3) every item in the array **mat_t** and print the result.

In [58]:
#if you had trouble with previous sections, and can't use mat_t, please use the following array instead.
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [99]:
#enter your answer here
print(np.power(mat_t, 3))

[[      1   15625  531441]
 [     64   46656 1000000]
 [    729  117649 1771561]
 [   4096  262144 2985984]]


## Section 7 - Reading a file manually

Get the file **loan_data_set.csv**.


In [62]:
!wget -O loan_data_set.zip "https://drive.google.com/uc?export=download&id=1BB_b2NQtWXWJw6OQbXXboPb3ONGsPp95"
!unzip loan_data_set.zip

--2023-11-20 10:10:47--  https://drive.google.com/uc?export=download&id=1BB_b2NQtWXWJw6OQbXXboPb3ONGsPp95
Resolving drive.google.com (drive.google.com)... 142.251.107.113, 142.251.107.138, 142.251.107.102, ...
Connecting to drive.google.com (drive.google.com)|142.251.107.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-14-80-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0u8ci1m7ngv3klp7kd886uaka1vno4d4/1700475000000/02584936932483403665/*/1BB_b2NQtWXWJw6OQbXXboPb3ONGsPp95?e=download&uuid=f3eb203c-7af5-4759-a0d5-0d5f4ee52421 [following]
--2023-11-20 10:10:47--  https://doc-14-80-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/0u8ci1m7ngv3klp7kd886uaka1vno4d4/1700475000000/02584936932483403665/*/1BB_b2NQtWXWJw6OQbXXboPb3ONGsPp95?e=download&uuid=f3eb203c-7af5-4759-a0d5-0d5f4ee52421
Resolving doc-14-80-docs.googleusercontent.com (doc-14-80-docs.googleusercontent.com)... 74.125.134.132, 2

### Q7.1: Reading the first 10 lines (6 marks)

* Using the standard Python functions (open(), read(), readlines(), write(), ...), print the content of the first 10 lines of the file to the screen.

In [67]:
#enter your answer here
with open('loan_data_set.csv','r') as f:
  count = 0
  lines = f.readlines()
  for line in lines:
    while(count < 10):
      print(line)
      count = count + 1
      break

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status

0,LP001002,Male,No,0,Graduate,No,46792,0.0,,360.0,1.0,Urban,Y

1,LP001003,Male,Yes,1,Graduate,No,36664,12064.0,1024.0,360.0,1.0,Rural,N

2,LP001005,Male,Yes,0,Graduate,Yes,24000,0.0,528.0,360.0,1.0,Urban,Y

3,LP001006,Male,Yes,0,Not Graduate,No,20664,18864.0,960.0,360.0,1.0,Urban,Y

4,LP001008,Male,No,0,Graduate,No,48000,0.0,1128.0,360.0,1.0,Urban,Y

5,LP001011,Male,Yes,2,Graduate,Yes,43336,33568.0,2136.0,360.0,1.0,Urban,Y

6,LP001013,Male,Yes,0,Not Graduate,No,18664,12128.0,760.0,360.0,1.0,Urban,Y

7,LP001014,Male,Yes,3+,Graduate,No,24288,20032.0,1264.0,360.0,0.0,Semiurban,N

8,LP001018,Male,Yes,2,Graduate,No,32048,12208.0,1344.0,360.0,1.0,Urban,Y



## Section 8 - Pandas

This time we are going to use Pandas to load the **loan_data_set.csv** file and explore it.

### Q8.1: Loading the CSV file (2 marks)

First of all, import the Pandas module! Using one of Pandas functions, load the data of the CSV file into a dataframe and assign it to a variable **df**.

In [70]:
#enter your answer here
import pandas as pd

df = pd.read_csv('loan_data_set.csv')

### Q8.2: Displaying the first 10 lines (2 marks)

Print the first 10 lines of your dataframe.

In [71]:
#enter your answer here
df.head(10)

Unnamed: 0   Loan_ID Gender Married Dependents     Education Self_Employed  \
0           0  LP001002   Male      No          0      Graduate            No   
1           1  LP001003   Male     Yes          1      Graduate            No   
2           2  LP001005   Male     Yes          0      Graduate           Yes   
3           3  LP001006   Male     Yes          0  Not Graduate            No   
4           4  LP001008   Male      No          0      Graduate            No   
5           5  LP001011   Male     Yes          2      Graduate           Yes   
6           6  LP001013   Male     Yes          0  Not Graduate            No   
7           7  LP001014   Male     Yes         3+      Graduate            No   
8           8  LP001018   Male     Yes          2      Graduate            No   
9           9  LP001020   Male     Yes          1      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0            46792                0.0         NaN             360.0   
1            36664            12064.0      1024.0             360.0   
2            24000                0.0       528.0             360.0   
3            20664            18864.0       960.0             360.0   
4            48000                0.0      1128.0             360.0   
5            43336            33568.0      2136.0             360.0   
6            18664            12128.0       760.0             360.0   
7            24288            20032.0      1264.0             360.0   
8            32048            12208.0      1344.0             360.0   
9           102728            87744.0      2792.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y  
6             1.0         Urban           Y  
7             0.0     Semiurban           N  
8             1.0         Urban           Y  
9             1.0     Semiurban           N

### Q8.3: Displaying the last 5 lines (1 mark)

Print the last 5 lines of your dataframe.

In [72]:
#enter your answer here
df.tail(5)

Unnamed: 0   Loan_ID  Gender Married Dependents Education Self_Employed  \
609         609  LP002978  Female      No          0  Graduate            No   
610         610  LP002979    Male     Yes         3+  Graduate            No   
611         611  LP002983    Male     Yes          1  Graduate            No   
612         612  LP002984    Male     Yes          2  Graduate            No   
613         613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609            23200                0.0       568.0             360.0   
610            32848                0.0       320.0             180.0   
611            64576             1920.0      2024.0             360.0   
612            60664                0.0      1496.0             360.0   
613            36664                0.0      1064.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

### Q8.4: Dataframe Shape (2 marks)

Print the shape of your dataframe.

In [73]:
#enter your answer here
df.shape

(614, 14)

### Q8.5: Column Names (2 marks)
Print out the column names of the data frame.

In [74]:
#enter your answer here
df.columns

Index(['Unnamed: 0', 'Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

### Q8.6: Extract one column (2 marks)

Print on the screen the column 'Education'.

In [76]:
#enter your answer here
print(df.Education)

0          Graduate
1          Graduate
2          Graduate
3      Not Graduate
4          Graduate
           ...     
609        Graduate
610        Graduate
611        Graduate
612        Graduate
613        Graduate
Name: Education, Length: 614, dtype: object


### Q8.7: Data summary (4 marks)

Print the number of Married and Non-Married individuals in the dataset using one line of code.

In [77]:
#enter your answer here
df.Married.value_counts()

Yes    398
No     213
Name: Married, dtype: int64

### Q8.8: Row filtering (4 marks)

Print the rows where the number of dependents is equal to 1 using one line of code.

In [98]:
#enter your answer here
df[df.Dependents == '1']

Unnamed: 0   Loan_ID  Gender Married Dependents     Education  \
1             1  LP001003    Male     Yes          1      Graduate   
9             9  LP001020    Male     Yes          1      Graduate   
16           16  LP001034    Male      No          1  Not Graduate   
21           21  LP001046    Male     Yes          1      Graduate   
24           24  LP001052    Male     Yes          1      Graduate   
..          ...       ...     ...     ...        ...           ...   
584         584  LP002911    Male     Yes          1      Graduate   
585         585  LP002912    Male     Yes          1      Graduate   
604         604  LP002959  Female     Yes          1      Graduate   
606         606  LP002961    Male     Yes          1      Graduate   
611         611  LP002983    Male     Yes          1      Graduate   

    Self_Employed  ApplicantIncome  CoapplicantIncome  LoanAmount  \
1              No            36664            12064.0      1024.0   
9              No           102728            87744.0      2792.0   
16             No            28768                0.0       800.0   
21             No            47640            45000.0      2520.0   
24            NaN            29736            23400.0      1208.0   
..            ...              ...                ...         ...   
584            No            22296            15336.0      1168.0   
585            No            34264            24000.0      1376.0   
604            No            96000                0.0      3968.0   
606            No            27200            20000.0      1384.0   
611            No            64576             1920.0      2024.0   

     Loan_Amount_Term  Credit_History Property_Area Loan_Status  TotalIncome  
1               360.0             1.0         Rural           N      48728.0  
9               360.0             1.0     Semiurban           N     190472.0  
16              240.0             NaN         Urban           Y      28768.0  
21              360.0             1.0         Urban           Y      92640.0  
24              360.0             NaN     Semiurban           N      53136.0  
..                ...             ...           ...         ...          ...  
584             360.0             0.0         Rural           N      37632.0  
585              84.0             1.0         Rural           N      58264.0  
604             360.0             1.0     Semiurban           Y      96000.0  
606             360.0             1.0     Semiurban           Y      47200.0  
611             360.0             1.0         Urban           Y      66496.0  

[102 rows x 15 columns]

### Q8.9: Column creation (2 marks)

Create a column 'TotalIncome' that sums the columns 'ApplicantIncome' and 'CoapplicantIncome'.

In [88]:
#enter your answer here
df['TotalIncome'] = df['ApplicantIncome'] + df['CoapplicantIncome']
df.head()

Unnamed: 0   Loan_ID Gender Married Dependents     Education Self_Employed  \
0           0  LP001002   Male      No          0      Graduate            No   
1           1  LP001003   Male     Yes          1      Graduate            No   
2           2  LP001005   Male     Yes          0      Graduate           Yes   
3           3  LP001006   Male     Yes          0  Not Graduate            No   
4           4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0            46792                0.0         NaN             360.0   
1            36664            12064.0      1024.0             360.0   
2            24000                0.0       528.0             360.0   
3            20664            18864.0       960.0             360.0   
4            48000                0.0      1128.0             360.0   

   Credit_History Property_Area Loan_Status  TotalIncome  
0             1.0         Urban           Y      46792.0  
1             1.0         Rural           N      48728.0  
2             1.0         Urban           Y      24000.0  
3             1.0         Urban           Y      39528.0  
4             1.0         Urban           Y      48000.0

### Q8.10 Filtering and Slicing (4 marks)
Print the columns 'Education' and 'Self_Employed' for the rows where 'Loan_Status' is 'N' using one line of code.

In [93]:
#enter your answer here
df_loan_status_no = df[df['Loan_Status'] == 'N']
print(df_loan_status_no['Education'])
print(df_loan_status_no['Self_Employed'])

1          Graduate
7          Graduate
9          Graduate
13         Graduate
17         Graduate
           ...     
596    Not Graduate
597        Graduate
600        Graduate
605    Not Graduate
613        Graduate
Name: Education, Length: 192, dtype: object
1       No
7       No
9       No
13      No
17      No
      ... 
596    Yes
597     No
600    NaN
605     No
613    Yes
Name: Self_Employed, Length: 192, dtype: object


## THIS IS THE END OF THE TEST (100 marks were available)